2022-06-24 15:09:50,290 - Client logged in
2022-06-24 15:09:50,290 - Server must be started before running this script
2022-06-24 15:42:25,481 - Client logged in
2022-06-24 15:42:25,481 - Server must be started before running this script
2022-06-24 15:42:36,818 - Client logged in
2022-06-24 15:42:36,818 - Server must be started before running this script
2022-06-24 15:45:39,798 - Client logged in
2022-06-24 15:45:39,798 - Server must be started before running this script
2022-06-24 15:45:51,777 - Client logged in
2022-06-24 15:45:51,777 - Server must be started before running this script
2022-06-24 15:55:09,578 - Client - Started
2022-06-24 15:55:09,578 - Server must be started before running this script
2022-06-24 15:55:45,090 - Client - Started
2022-06-24 15:55:45,090 - Server must be started before running this script
2022-06-24 15:55:45,090 - modulo es (1, 2, 3, 4 , 5)
2022-06-24 15:58:50,422 - Client - Started
2022-06-24 15:58:50,422 - Server must be started before running this script
2022-06-24 15:58:50,422 - modulo es (1, 2, 3, 4 , 5)
2022-06-24 16:01:03,604 - Client - Started
2022-06-24 16:01:03,604 - Server must be started before running this script
2022-06-24 16:01:03,604 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:03:50,845 - Client - Started
2022-06-24 16:03:50,845 - Server must be started before running this script
2022-06-24 16:03:50,845 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:03:57,473 - Client - Started
2022-06-24 16:03:57,473 - Server must be started before running this script
2022-06-24 16:03:57,473 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:04:19,361 - Client - Started
2022-06-24 16:04:19,361 - Server must be started before running this script
2022-06-24 16:04:19,362 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:07:56,048 - Client - Started
2022-06-24 16:07:56,048 - Server must be started before running this script
2022-06-24 16:07:56,048 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:08:01,503 - Exception occurred
Traceback (most recent call last):
  File "logging-client.py", line 32, in <module>
    for key, value in data.items():
AttributeError: 'bytes' object has no attribute 'items'
2022-06-24 16:08:53,280 - Client - Started
2022-06-24 16:08:53,280 - Server must be started before running this script
2022-06-24 16:08:53,280 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:11:40,146 - Client - Started
2022-06-24 16:11:40,146 - Server must be started before running this script
2022-06-24 16:11:40,146 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:12:26,603 - Client - Started
2022-06-24 16:12:26,603 - Server must be started before running this script
2022-06-24 16:12:26,603 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:12:53,318 - Client - Started
2022-06-24 16:12:53,318 - Server must be started before running this script
2022-06-24 16:12:53,318 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:13:15,501 - Client - Started
2022-06-24 16:13:15,501 - Server must be started before running this script
2022-06-24 16:13:15,501 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:14:47,504 - Client - Started
2022-06-24 16:14:47,504 - Server must be started before running this script
2022-06-24 16:14:47,504 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:14:49,895 - Exception occurred
Traceback (most recent call last):
  File "logging-client.py", line 34, in <module>
    print(json_object["module"])
KeyError: 'module'
2022-06-24 16:15:05,820 - Client - Started
2022-06-24 16:15:05,820 - Server must be started before running this script
2022-06-24 16:15:05,820 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:15:10,193 - Exception occurred
Traceback (most recent call last):
  File "logging-client.py", line 34, in <module>
    print(json_object['module'])
KeyError: 'module'
2022-06-24 16:17:35,582 - Client - Started
2022-06-24 16:17:35,582 - Server must be started before running this script
2022-06-24 16:17:35,582 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:17:42,153 - Exception occurred
Traceback (most recent call last):
  File "logging-client.py", line 34, in <module>
    a=json_object["module"]
KeyError: 'module'
2022-06-24 16:17:43,474 - Client - Started
2022-06-24 16:17:43,474 - Server must be started before running this script
2022-06-24 16:17:43,474 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:17:59,631 - Exception occurred
Traceback (most recent call last):
  File "logging-client.py", line 34, in <module>
    a=json_object["module"]
KeyError: 'module'
2022-06-24 16:18:44,587 - Client - Started
2022-06-24 16:18:44,587 - Server must be started before running this script
2022-06-24 16:18:44,587 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:19:10,869 - Client - Started
2022-06-24 16:19:10,869 - Server must be started before running this script
2022-06-24 16:19:10,869 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:19:15,288 - Exception occurred
Traceback (most recent call last):
  File "logging-client.py", line 34, in <module>
    print(json_object[0])
KeyError: 0
2022-06-24 16:20:55,304 - Client - Started
2022-06-24 16:20:55,304 - Server must be started before running this script
2022-06-24 16:20:55,304 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:20:59,778 - Exception occurred
Traceback (most recent call last):
  File "logging-client.py", line 35, in <module>
    print(json_object["state"])
KeyError: 'state'
2022-06-24 16:32:30,974 - Client - Started
2022-06-24 16:32:31,010 - Server must be started before running this script
2022-06-24 16:32:31,010 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:32:32,012 - Exception occurred
Traceback (most recent call last):
  File "logging-client.py", line 35, in <module>
    print(json_object["state"])
KeyError: 'state'
2022-06-24 16:33:12,403 - Client - Started
2022-06-24 16:33:12,403 - Server must be started before running this script
2022-06-24 16:33:12,403 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:33:39,416 - Client - Started
2022-06-24 16:33:39,417 - Server must be started before running this script
2022-06-24 16:33:39,417 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 16:33:43,825 - Client - Started
2022-06-24 16:33:43,825 - Server must be started before running this script
2022-06-24 16:33:43,825 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 17:41:57,925 - Client - Started
2022-06-24 17:41:57,951 - Server must be started before running this script
2022-06-24 17:41:57,951 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 17:42:29,735 - Client - Started
2022-06-24 17:42:29,735 - Server must be started before running this script
2022-06-24 17:42:29,735 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 17:55:08,571 - Client - Started
2022-06-24 17:55:08,571 - Server must be started before running this script
2022-06-24 17:55:08,571 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 17:55:12,391 - Exception occurred
Traceback (most recent call last):
  File "logging-client.py", line 35, in <module>
    for i in data['messages']:
TypeError: byte indices must be integers or slices, not str
2022-06-24 17:56:59,086 - Client - Started
2022-06-24 17:56:59,086 - Server must be started before running this script
2022-06-24 17:56:59,086 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 17:57:04,566 - Exception occurred
Traceback (most recent call last):
  File "logging-client.py", line 33, in <module>
    json_object = json.load(data)
  File "/home/jose/anaconda3/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
AttributeError: 'bytes' object has no attribute 'read'
2022-06-24 17:57:26,123 - Client - Started
2022-06-24 17:57:26,123 - Server must be started before running this script
2022-06-24 17:57:26,123 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 17:57:31,661 - Exception occurred
Traceback (most recent call last):
  File "logging-client.py", line 33, in <module>
    json_object = json.load(data)
  File "/home/jose/anaconda3/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
AttributeError: 'bytes' object has no attribute 'read'
2022-06-24 17:57:43,831 - Client - Started
2022-06-24 17:57:43,831 - Server must be started before running this script
2022-06-24 17:57:43,831 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 17:58:22,077 - Client - Started
2022-06-24 17:58:22,077 - Server must be started before running this script
2022-06-24 17:58:22,077 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 17:59:30,338 - Client - Started
2022-06-24 17:59:30,338 - Server must be started before running this script
2022-06-24 17:59:30,338 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 17:59:33,707 - Exception occurred
Traceback (most recent call last):
  File "logging-client.py", line 35, in <module>
    for i in data['messages']:
TypeError: byte indices must be integers or slices, not str
2022-06-24 18:13:07,001 - Client - Started
2022-06-24 18:13:07,025 - Server must be started before running this script
2022-06-24 18:13:07,025 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:13:31,979 - Client - Started
2022-06-24 18:13:31,979 - Server must be started before running this script
2022-06-24 18:13:31,979 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:15:30,882 - Client - Started
2022-06-24 18:15:30,882 - Server must be started before running this script
2022-06-24 18:15:30,882 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:16:14,215 - Client - Started
2022-06-24 18:16:14,215 - Server must be started before running this script
2022-06-24 18:16:14,215 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:25:10,991 - Client - Started
2022-06-24 18:25:11,014 - Server must be started before running this script
2022-06-24 18:25:11,015 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:26:03,547 - Client - Started
2022-06-24 18:26:03,547 - Server must be started before running this script
2022-06-24 18:26:03,548 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:26:28,025 - Client - Started
2022-06-24 18:26:28,025 - Server must be started before running this script
2022-06-24 18:26:28,025 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:27:01,687 - Client - Started
2022-06-24 18:27:01,687 - Server must be started before running this script
2022-06-24 18:27:01,687 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:27:49,774 - Client - Started
2022-06-24 18:27:49,774 - Server must be started before running this script
2022-06-24 18:27:49,774 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:28:11,793 - Client - Started
2022-06-24 18:28:11,793 - Server must be started before running this script
2022-06-24 18:28:11,793 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:28:35,457 - Client - Started
2022-06-24 18:28:35,457 - Server must be started before running this script
2022-06-24 18:28:35,457 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:29:10,818 - Client - Started
2022-06-24 18:29:10,818 - Server must be started before running this script
2022-06-24 18:29:10,818 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:31:15,273 - Client - Started
2022-06-24 18:31:15,274 - Server must be started before running this script
2022-06-24 18:31:15,274 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:31:41,141 - Client - Started
2022-06-24 18:31:41,141 - Server must be started before running this script
2022-06-24 18:31:41,141 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:31:42,143 - Exception occurred
Traceback (most recent call last):
  File "logging-client.py", line 42, in <module>
    print (json_object[0])
KeyError: 0
2022-06-24 18:32:11,031 - Client - Started
2022-06-24 18:32:11,032 - Server must be started before running this script
2022-06-24 18:32:11,032 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:32:14,939 - Exception occurred
Traceback (most recent call last):
  File "logging-client.py", line 42, in <module>
    print (json_object[1])
KeyError: 1
2022-06-24 18:33:39,336 - Client - Started
2022-06-24 18:33:39,336 - Server must be started before running this script
2022-06-24 18:33:39,337 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:34:10,159 - Client - Started
2022-06-24 18:34:10,159 - Server must be started before running this script
2022-06-24 18:34:10,159 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:38:46,801 - Client - Started
2022-06-24 18:38:46,801 - Server must be started before running this script
2022-06-24 18:38:46,801 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:41:35,741 - Client - Started
2022-06-24 18:41:35,741 - Server must be started before running this script
2022-06-24 18:41:35,741 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:42:09,938 - Client - Started
2022-06-24 18:42:09,939 - Server must be started before running this script
2022-06-24 18:42:09,939 - modulo es (a, 2, 3, 4 , 5)
2022-06-24 18:42:44,753 - Client - Started
2022-06-24 18:42:44,753 - Server must be started before running this script
2022-06-24 18:42:44,753 - modulo es (a, 2, 3, 4 , 5)
